/**
 * DepEd Daily Lesson Plan (DLP) Heading Parser & Section Extractor
 * Based on Cambaog National High School DepEd DLP Format (DO 42 s. 2016 / DO 3 s. 2026)
 */

export const DEPED_SECTIONS = [
  {
    key: "intentions",
    title: "I. Intentions & Objectives",
    subtitle: "Competencies, Session 1-5 Objectives (Cognitive, Affective, Psychomotor)",
    icon: "Target",
    badge: "Core",
  },
  {
    key: "learner_context",
    title: "II. Learner Context & Observations",
    subtitle: "Strengths, interests, barriers to learning, and accommodations",
    icon: "Users",
    badge: "Context",
  },
  {
    key: "pre_lesson",
    title: "III. Pre-Lesson Preparation",
    subtitle: "Prayer, greetings, classroom management, attendance, and review",
    icon: "Clock",
    badge: "Prep",
  },
  {
    key: "flow",
    title: "IV. Learning Flow & Session Activities",
    subtitle: "Lesson purpose, discussion, reading, exercises, and synthesis",
    icon: "BookOpen",
    badge: "Delivery",
  },
  {
    key: "resources_integration",
    title: "V. Learning Resources & Integration",
    subtitle: "Materials, worksheets, tech tools, Values, AP, ICT integration",
    icon: "Layers",
    badge: "Resources",
  },
  {
    key: "assessment",
    title: "VI. Formative Assessment",
    subtitle: "Tasks, questions, evaluation rubrics, and feedback mechanisms",
    icon: "CheckSquare",
    badge: "Assessment",
  },
  {
    key: "ways_forward",
    title: "VII. Ways Forward & Reflections",
    subtitle: "Extended learning opportunities, remediation, and teacher reflections",
    icon: "Sparkles",
    badge: "Reflection",
  },
  {
    key: "signatories_ai",
    title: "VIII. Declaration & Signatories",
    subtitle: "AI use disclosure (DO 3 s.2026), Prepared by Teacher, Checked by Principal",
    icon: "FileCheck",
    badge: "Compliance",
  },
];

/**
 * Extracts structured sections from raw HTML (generated by Mammoth from .docx)
 * or falls back to sensible structure for PDF / raw text.
 */
export function extractDepEdSectionsFromHtml(html = "", metadata = {}) {
  if (!html || typeof html !== "string") {
    return createDefaultSections(metadata);
  }

  if (typeof window !== "undefined" && window.DOMParser) {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, "text/html");
      const text = doc.body.textContent || "";
      return parseFromTextAndTables(doc, text, metadata);
    } catch (e) {
      console.warn("[docxParser] DOMParser failed, using regex fallback", e);
    }
  }

  return parseWithRegexFallback(html, metadata);
}

function parseFromTextAndTables(doc, fullText, metadata) {
  const sections = {};
  DEPED_SECTIONS.forEach((s) => {
    sections[s.key] = {
      ...s,
      content: "",
      found: false,
    };
  });

  const tables = doc.querySelectorAll("table");
  if (tables && tables.length > 0) {
    tables.forEach((table) => {
      const rows = table.querySelectorAll("tr");
      rows.forEach((row) => {
        const text = row.textContent || "";
        const lower = text.toLowerCase();

        if (lower.includes("intentions") || lower.includes("competency") || lower.includes("learning objectives")) {
          sections.intentions.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.intentions.found = true;
        } else if (lower.includes("learner context") || lower.includes("observations of your learners") || lower.includes("barriers to learning")) {
          sections.learner_context.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.learner_context.found = true;
        } else if (lower.includes("pre-lesson") || lower.includes("get ready for the lesson") || lower.includes("classroom management")) {
          sections.pre_lesson.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.pre_lesson.found = true;
        } else if (lower.includes("flow") || lower.includes("learning experience") || lower.includes("lesson purpose") || lower.includes("discussion") || lower.includes("popcorn")) {
          sections.flow.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.flow.found = true;
        } else if (lower.includes("learning resources") || lower.includes("opportunities for integration") || lower.includes("values education") || lower.includes("i.c.t")) {
          sections.resources_integration.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.resources_integration.found = true;
        } else if (lower.includes("assessment") || lower.includes("formative assessment") || lower.includes("evaluate learning")) {
          sections.assessment.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.assessment.found = true;
        } else if (lower.includes("ways forward") || lower.includes("extended learning") || lower.includes("reflections")) {
          sections.ways_forward.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.ways_forward.found = true;
        } else if (lower.includes("declaration of ai use") || lower.includes("prepared by") || lower.includes("checked by") || lower.includes("school principal")) {
          sections.signatories_ai.content += `<div class="p-2.5 rounded-lg bg-slate-50 dark:bg-white/5 my-1.5 border border-slate-100 dark:border-white/5">${row.innerHTML}</div>`;
          sections.signatories_ai.found = true;
        }
      });
    });
  }

  const allParagraphs = doc.querySelectorAll("p, h1, h2, h3, h4");
  allParagraphs.forEach((p) => {
    const text = p.textContent || "";
    const lower = text.toLowerCase();
    if (!sections.signatories_ai.found && (lower.includes("ai use") || lower.includes("checked by") || lower.includes("principal"))) {
      sections.signatories_ai.content += `<p class="my-1">${p.innerHTML}</p>`;
      sections.signatories_ai.found = true;
    }
  });

  Object.keys(sections).forEach((key) => {
    if (!sections[key].found || !sections[key].content.trim()) {
      sections[key].content = getSectionPlaceholder(key, metadata);
    }
  });

  return Object.values(sections);
}

function parseWithRegexFallback(html, metadata) {
  const sections = {};
  DEPED_SECTIONS.forEach((s) => {
    sections[s.key] = {
      ...s,
      content: getSectionPlaceholder(s.key, metadata),
      found: false,
    };
  });
  return Object.values(sections);
}

function createDefaultSections(metadata = {}) {
  return DEPED_SECTIONS.map((s) => ({
    ...s,
    content: getSectionPlaceholder(s.key, metadata),
    found: true,
  }));
}

function getSectionPlaceholder(key, metadata = {}) {
  switch (key) {
    case "intentions":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p class="font-semibold text-slate-800 dark:text-slate-100 mb-1">Learning Competency & Curriculum Standards:</p>
        <p class="mb-2 italic">${metadata.lessonTitle || "Analyze literary texts as expressions of individual or communal values."}</p>
        <p class="font-semibold text-slate-800 dark:text-slate-100 mb-1">Sessions 1–5 Objectives:</p>
        <ul class="list-disc pl-4 space-y-1 text-slate-600 dark:text-slate-400">
          <li><strong>Cognitive:</strong> Define concepts, identify key details, explain thematic conflicts.</li>
          <li><strong>Affective:</strong> Value cooperation, family relationships, and moral principles.</li>
          <li><strong>Psychomotor:</strong> Complete semantic webs, worksheets, and oral response activities.</li>
        </ul>
      </div>`;
    case "learner_context":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p>• Learners connect familiar everyday examples with target literature concepts.</p>
        <p>• Group reading and graphic organizers are utilized for differentiated learner support.</p>
      </div>`;
    case "pre_lesson":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p>• Prayer, Greetings, Attendance Check, and Classroom Management.</p>
        <p>• Short Review & Concept Activation prompt for ${metadata.learningArea || "English"}.</p>
      </div>`;
    case "flow":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p class="font-semibold text-slate-800 dark:text-slate-100 mb-1">Delivery Flow across Sessions:</p>
        <p>1. Lesson Purpose & Vocabulary Unlocking</p>
        <p>2. Reading Passage / Group Story Analysis</p>
        <p>3. Guided Comprehension Questions & Discussion</p>
        <p>4. Practical Application & Synthesis</p>
      </div>`;
    case "resources_integration":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p>• <strong>Learning Resources:</strong> Lesson Exemplar, Worksheets, Slides, Story Copies.</p>
        <p>• <strong>Integration:</strong> Values Education (Respect & Fairness), Araling Panlipunan (Social Context), TLE/ICT (Digital Media).</p>
      </div>`;
    case "assessment":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p class="font-semibold text-slate-800 dark:text-slate-100 mb-1">Formative Assessment:</p>
        <p>Road Map worksheet answers, Comprehension Yes/No validation, Short story elements identification, and rubric-based oral participation.</p>
      </div>`;
    case "ways_forward":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p class="font-semibold text-slate-800 dark:text-slate-100 mb-1">Extended Learning & Reflection:</p>
        <p>Home reading reinforcement, thematic family interview questions, and teacher reflection on learner mastery.</p>
      </div>`;
    case "signatories_ai":
      return `<div class="text-xs text-slate-600 dark:text-slate-300">
        <p class="mb-1"><strong>AI Use Declaration:</strong> AI was used in accordance with DO 3 s.2026 Annex A to format and structure the prescribed DLP template.</p>
        <div class="mt-2 pt-2 border-t border-slate-200 dark:border-white/10 flex justify-between">
          <div><p class="text-[10px] uppercase text-slate-400">Prepared by:</p><p class="font-bold text-slate-700 dark:text-slate-200">${metadata.teacher || "Subject Teacher"}</p></div>
          <div><p class="text-[10px] uppercase text-slate-400">Checked by:</p><p class="font-bold text-slate-700 dark:text-slate-200">Dulce Vilma R. Galang (School Principal)</p></div>
        </div>
      </div>`;
    default:
      return `<div class="text-xs text-slate-500 italic">Content parsed from submitted lesson plan.</div>`;
  }
}
