import { downloadWorkbook } from "@/lib/reports/excelOfficialTemplate";
import { buildTeacherClassExcelReport } from "@/lib/reports/excelTeacherClassTemplate";
import {
  chartRowsFromList,
  escapeHtml,
  renderBarChartHtml,
  renderDataTableHtml,
  renderMetricGroupsHtml,
  wrapCnhsPrintDocument,
} from "@/lib/reports/cnhsPrintShell";
import { openPrintableHtml } from "@/lib/reports/openPrintableHtml";
import { buildTeacherExcelPayload } from "@/lib/reports/scopedExcelPayload";
import { TERM_ALL_LABEL, termLabel } from "@/lib/academic/termLabels";
import { passingRateFromGrades } from "@/lib/teacher/reportsCalculations";

/**
 * Open a printable HTML report (browser Print → Save as PDF).
 * CNHS-branded shell (same look as Class Performance System Report).
 */
export function exportTeacherReportsPdf({
  teacherName,
  schoolYear,
  quarter,
  summary,
  classReports = [],
  charts = {},
  generatedAt = new Date(),
} = {}) {
  const dateGenerated = generatedAt.toLocaleString("en-PH", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const summaryHtml = renderMetricGroupsHtml([
    {
      label: "Scope",
      metrics: [
        ["Total classes", summary?.totalClasses ?? 0],
        ["Total learners", summary?.totalStudents ?? 0],
      ],
    },
    {
      label: "Academic",
      metrics: [
        [
          "Average class grade",
          summary?.averageClassGrade == null
            ? "—"
            : summary.averageClassGrade,
        ],
        [
          "Passing rate",
          summary?.passingRate == null ? "—" : `${summary.passingRate}%`,
        ],
        ["Highest subject", summary?.highestSubject || "—"],
        ["Lowest subject", summary?.lowestSubject || "—"],
      ],
    },
    {
      label: "Intervention",
      metrics: [
        ["ARAL learners", summary?.aralScreeningCount ?? 0],
        ["Classroom remedial", summary?.classroomRemedialCount ?? 0],
        [
          "Monitoring completion",
          `${summary?.monitoringCompletionRate ?? 0}%`,
        ],
        [
          "Under monitoring",
          summary?.learnersUnderMonitoring ?? 0,
        ],
      ],
    },
  ]);

  const tableRows = classReports
    .map(
      (row) => `<tr>
        <td>${escapeHtml(row.section ?? row.gradeSection)}</td>
        <td>${escapeHtml(row.subject)}</td>
        <td>${escapeHtml(row.students)}</td>
        <td>${escapeHtml(row.averageGrade)}</td>
        <td>${escapeHtml(row.aralScreeningDisplay ?? (row.aralEligible === false ? "—" : row.aralScreening))}</td>
        <td>${escapeHtml(row.classroomRemedial)}</td>
        <td>${escapeHtml(row.monitoringStatus)}</td>
      </tr>`
    )
    .join("");

  const bodyHtml = `
    <p class="section-label">Summary</p>
    ${summaryHtml}

    <p class="section-label">Class Reports</p>
    ${renderDataTableHtml({
      headers: [
        "Section",
        "Subject",
        "Students",
        "Average Grade",
        "ARAL Learners",
        "Classroom Remedial",
        "Monitoring Status",
      ],
      rowsHtml: tableRows,
      emptyText: "No class reports for the selected filters.",
    })}

    <p class="section-label">Charts</p>
    <div class="charts">
      ${renderBarChartHtml(
        "Student Performance Distribution",
        chartRowsFromList(charts.performanceDistribution)
      )}
      ${renderBarChartHtml(
        "ARAL Learners Distribution",
        chartRowsFromList(charts.aralDistribution)
      )}
      ${renderBarChartHtml(
        "Average Grade Per Subject",
        chartRowsFromList(
          charts.averageGradePerSubject,
          "subject",
          "average"
        )
      )}
      ${renderBarChartHtml(
        "Monitoring Progress",
        chartRowsFromList(charts.monitoringProgress)
      )}
    </div>
  `;

  const html = wrapCnhsPrintDocument({
    documentTitle: `Teacher Report — ${teacherName || "CNHS"}`,
    letterheadSub: "CNHS Learn · Teacher Class Performance Report",
    title: "TEACHER CLASS PERFORMANCE REPORT",
    subtitle: `${schoolYear || "—"} · ${quarter || "—"}`,
    metaRows: [
      ["Generated by", teacherName || "Teacher"],
      ["Coverage", schoolYear || "—"],
      ["Report category", "Academic performance"],
      ["Term", quarter || "—"],
      ["Report type", "Multi-class summary"],
      ["Date generated", dateGenerated],
    ],
    bodyHtml,
    signatureLabel: "Prepared and certified by Subject Teacher / Adviser:",
  });

  openPrintableHtml(html, {
    title: `Teacher-Report-${teacherName || "CNHS"}`,
    autoPrint: true,
  });
}

function resolveTermLabel(quarter) {
  if (!quarter) return TERM_ALL_LABEL;
  return termLabel(quarter);
}

function formatSchoolYearForFilename(value) {
  const year = String(value ?? "").trim();
  if (!year) return "SY";
  if (/^sy\b/i.test(year)) return year;
  return `SY ${year}`;
}

function windowsSafeFilename(name) {
  return (
    String(name ?? "")
      .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 150) || "Teacher Report"
  );
}

function gradeSectionForFilename(classReports = []) {
  const sections = [
    ...new Set(
      classReports
        .map((row) => row?.gradeSection || row?.section)
        .map((value) => String(value ?? "").trim())
        .filter(Boolean)
    ),
  ];
  if (sections.length === 1) return sections[0];
  return "All Classes";
}

/** {Teacher Name} — {Grade & Section} — {School Year} — {Term}.xlsx */
function teacherClassReportFilename({
  teacherName,
  gradeSection,
  schoolYear,
  quarter,
} = {}) {
  const name = String(teacherName || "Teacher").trim() || "Teacher";
  const section =
    String(gradeSection || "All Classes").trim() || "All Classes";
  const year = formatSchoolYearForFilename(schoolYear);
  const term = resolveTermLabel(quarter);
  return `${windowsSafeFilename(`${name} — ${section} — ${year} — ${term}`)}.xlsx`;
}

function normalizeTeacherClassRow(row) {
  if (!row) return null;
  return {
    section: row.section ?? row.gradeSection,
    subject: row.subject,
    students: row.students,
    averageGrade: row.averageGrade,
    averageGradeValue:
      typeof row.averageGrade === "number"
        ? row.averageGrade
        : row.averageGradeValue ?? null,
    aralScreeningDisplay:
      row.aralScreeningDisplay ??
      (row.aralEligible === false ? "—" : row.aralScreening),
    classroomRemedial: row.classroomRemedial ?? "—",
    monitoringStatus: row.monitoringStatus ?? "—",
    schoolYear: row.schoolYear,
    quarter: row.quarter,
    teacherName: row.teacherName,
    aralEligible: row.aralEligible,
    aralScreening: row.aralScreening,
    classroomRemedialRecommended: Boolean(row.classroomRemedialRecommended),
    classStudents: row.classStudents,
    subjectGrades: row.subjectGrades,
  };
}

function reportScopeLabel(classReports = []) {
  if (classReports.length === 1) {
    const row = classReports[0];
    const section = String(row?.gradeSection || row?.section || "").trim();
    const subject = String(row?.subject || "").trim();
    return [section, subject].filter(Boolean).join(" — ") || "All Classes";
  }
  return gradeSectionForFilename(classReports);
}

function buildTeacherCoverChartSeries(charts = {}) {
  const size = { width: 420, height: 240 };
  const series = [];

  if (charts.performanceDistribution?.length) {
    series.push({
      title: "Student Performance Distribution",
      tableTitle: "Student Performance",
      chartType: "pie",
      categoryHeader: "Band",
      valueHeader: "Learners",
      footer: "total",
      ...size,
      rows: charts.performanceDistribution.map((row) => ({
        category: row.name,
        value: row.value,
      })),
    });
  }

  if (charts.averageGradePerSubject?.length) {
    series.push({
      title: "Average Grade Per Subject",
      chartType: "bar",
      categoryHeader: "Subject",
      valueHeader: "Average",
      footer: "average",
      ...size,
      rows: charts.averageGradePerSubject.map((row) => ({
        category: row.subject ?? row.name,
        value: row.average ?? row.value,
      })),
    });
  }

  if (charts.monitoringProgress?.length) {
    series.push({
      title: "Monitoring Progress",
      chartType: "pie",
      categoryHeader: "Status",
      valueHeader: "Count",
      footer: "total",
      ...size,
      rows: charts.monitoringProgress.map((row) => ({
        category: row.name,
        value: row.value,
      })),
    });
  }

  return series;
}

function subjectAverageExtremes(rows = []) {
  const values = rows
    .map((row) => Number(row.average ?? row.value))
    .filter((n) => Number.isFinite(n));
  if (!values.length) return { highest: null, lowest: null };
  return {
    highest: Math.max(...values),
    lowest: Math.min(...values),
  };
}

/**
 * Export class report rows to official CNHS Excel workbook.
 * Cover metrics, charts, table, and narratives all use the same scoped payload.
 */
export async function exportTeacherReportsExcel({
  classReports = [],
  summary = {},
  charts = {},
  teacherName = "Teacher",
  schoolYear = "",
  quarter = "",
  filename = null,
} = {}) {
  const rows = classReports.map(normalizeTeacherClassRow).filter(Boolean);
  const scoped = buildTeacherExcelPayload({
    classReports: classReports.filter(Boolean),
    summary,
    charts,
  });
  const qLabel = resolveTermLabel(quarter);
  const {
    totalClasses,
    totalStudents,
    aralScreeningCount: aralLearners,
    classroomRemedialCount: classroomRemedial,
    averageClassGrade: averageGrade,
    monitoringCompletionRate: monitoringRate,
  } = scoped.summary;
  const { highest, lowest } = subjectAverageExtremes(
    scoped.charts.averageGradePerSubject
  );

  const workbook = await buildTeacherClassExcelReport({
    meta: {
      reportTitle: "Teacher Class Performance Report",
      schoolYear: schoolYear || "—",
      quarter: qLabel,
      generatedBy: teacherName || "Teacher",
      totalRecords: rows.length,
      reportScope: reportScopeLabel(classReports),
    },
    metrics: [
      { label: "Total Classes", value: totalClasses, tone: "default" },
      { label: "Total Students", value: totalStudents, tone: "default" },
      {
        label: "ARAL Learners",
        value: aralLearners,
        tone: Number(aralLearners) > 0 ? "amber" : "green",
      },
      {
        label: "Classroom Remedial Classes",
        value: classroomRemedial,
        tone: Number(classroomRemedial) > 0 ? "amber" : "green",
      },
      {
        label: "Average Class Grade",
        value: averageGrade ?? "—",
        tone:
          averageGrade != null && Number(averageGrade) < 75 ? "amber" : "green",
      },
      {
        label: "Monitoring Completion",
        value: `${monitoringRate}%`,
        tone: Number(monitoringRate) < 100 ? "amber" : "green",
      },
    ],
    chartSeries: buildTeacherCoverChartSeries(scoped.charts),
    table: {
      sheetName: "Detailed Report",
      title: `Class Reports — ${teacherName || "Teacher"} · ${schoolYear || "SY"} · ${qLabel}`,
      columns: [
        { key: "section", header: "Section", width: 18 },
        { key: "subject", header: "Subject", width: 16 },
        { key: "students", header: "Students", width: 11, numeric: true },
        {
          key: "averageGrade",
          header: "Avg Grade",
          width: 12,
          numeric: true,
          gradeRule: true,
        },
        { key: "aralScreeningDisplay", header: "ARAL Learners", width: 14 },
        { key: "classroomRemedial", header: "Classroom Remedial", width: 18 },
        {
          key: "monitoringStatus",
          header: "Monitoring Status",
          width: 18,
          statusRule: true,
        },
      ],
      rows,
    },
    narrativeContext: {
      totalClasses,
      totalStudents,
      averageGrade,
      highestAverage: highest,
      lowestAverage: lowest,
      atRisk: scoped.atRisk,
      aralLearners,
      classroomRemedial,
      monitoringRate,
    },
  });

  const resolvedFilename =
    filename ||
    teacherClassReportFilename({
      teacherName,
      gradeSection: gradeSectionForFilename(classReports),
      schoolYear,
      quarter,
    });

  await downloadWorkbook(workbook, resolvedFilename);
}

/**
 * Export a single class workbook — summary + charts rebuilt for that class only.
 */
export async function exportClassReportExcel(classReport, charts = {}) {
  if (!classReport) return;

  const filename = teacherClassReportFilename({
    teacherName: classReport.teacherName,
    gradeSection: classReport.gradeSection ?? classReport.section,
    schoolYear: classReport.schoolYear,
    quarter: classReport.quarter,
  });

  await exportTeacherReportsExcel({
    classReports: [classReport],
    summary: {},
    charts,
    teacherName: classReport.teacherName,
    schoolYear: classReport.schoolYear,
    quarter: classReport.quarter,
    filename,
  });
}

export async function exportSingleClassReportExcel(classReport, charts = {}) {
  if (!classReport) return;
  await exportClassReportExcel(classReport, charts);
}

function gradeBucketLabel(grade) {
  const n =
    grade === null || grade === undefined || grade === ""
      ? NaN
      : Number(grade);
  if (!Number.isFinite(n)) return "Ungraded";
  if (n >= 90) return "90-100";
  if (n >= 85) return "85-89";
  if (n >= 75) return "75-84";
  return "Below 75";
}

/** True when learner has no usable subject/term grade. */
function isUngradedGrade(grade) {
  if (grade === null || grade === undefined || grade === "" || grade === "—") {
    return true;
  }
  return !Number.isFinite(Number(grade));
}

function resolveLearnerGrade(student) {
  return student?.classSubjectGrade ?? student?.grade ?? student?.averageGrade;
}

/**
 * Risk for reports: Ungraded → "—"; only graded learners can be High/at-risk.
 */
function learnerRiskLabel(student) {
  const grade = resolveLearnerGrade(student);
  if (isUngradedGrade(grade)) return "—";
  const n = Number(grade);
  if (n < 75) return student.riskLevel === "Moderate" ? "Moderate" : "High";
  if (n <= 84) return student.riskLevel === "High" ? "High" : "Moderate";
  return student.riskLevel === "High" || student.riskLevel === "Moderate"
    ? student.riskLevel
    : "Low";
}

function isGradedAtRisk(student) {
  const grade = resolveLearnerGrade(student);
  if (isUngradedGrade(grade)) return false;
  const n = Number(grade);
  if (n < 75) return true;
  if (student.atRisk && n < 85) return true;
  return student.riskLevel === "High" && n < 85;
}

function buildClassPerfBuckets(classStudents = []) {
  const order = ["90-100", "85-89", "75-84", "Below 75", "Ungraded"];
  const counts = Object.fromEntries(order.map((k) => [k, 0]));
  for (const s of classStudents) {
    counts[gradeBucketLabel(resolveLearnerGrade(s))] += 1;
  }
  return order
    .filter((k) => k !== "Ungraded" || counts[k] > 0)
    .map((name) => ({ name, value: counts[name] }));
}

function buildClassMonitoringBars(classStudents = []) {
  const labels = [
    "Not Started",
    "Ongoing",
    "Needs Follow-up",
    "Improved",
    "Completed",
  ];
  const counts = Object.fromEntries(labels.map((k) => [k, 0]));
  for (const s of classStudents) {
    const status = String(s.monitoringStatus || "Not Started");
    if (counts[status] != null) counts[status] += 1;
    else counts["Not Started"] += 1;
  }
  return labels.map((name) => ({ name, value: counts[name] }));
}

/**
 * Formal one-class Class Performance System Report (printable HTML → PDF).
 * CNHS-branded letterhead; ungraded learners are not high risk.
 */
export function exportClassPerformanceSystemReport({
  classReport,
  teacherName,
  schoolYear,
  quarter,
  generatedAt = new Date(),
} = {}) {
  if (!classReport) throw new Error("Select a class to generate a report.");

  const dateGenerated = generatedAt.toLocaleString("en-PH", {
    dateStyle: "long",
    timeStyle: "short",
  });
  const section =
    classReport.gradeSection || classReport.section || "Section";
  const subject = classReport.subject || "Subject";
  const students = classReport.classStudents ?? [];
  const avg =
    classReport.averageGradeValue ?? classReport.averageGrade ?? "—";
  const passRate = passingRateFromGrades(classReport.subjectGrades);
  const passLabel = passRate == null ? "—" : `${passRate}%`;
  const aralCount =
    classReport.aralEligible === false ? 0 : classReport.aralScreening ?? 0;
  const ungradedCount = students.filter((s) =>
    isUngradedGrade(resolveLearnerGrade(s))
  ).length;
  const atRisk = students.filter((s) => isGradedAtRisk(s)).length;

  const perfBars = buildClassPerfBuckets(students);
  const monBars = buildClassMonitoringBars(students);

  const learnerRows = students
    .slice()
    .sort((a, b) =>
      String(a.name || "").localeCompare(String(b.name || ""), "en")
    )
    .map((s, index) => {
      const rawGrade = resolveLearnerGrade(s);
      const ungraded = isUngradedGrade(rawGrade);
      const grade = ungraded ? "Ungraded" : rawGrade;
      const risk = learnerRiskLabel(s);
      const aral = ungraded
        ? "—"
        : s.recommendationDisplay ||
          (String(s.recommendation || "").toLowerCase().includes("aral")
            ? "ARAL"
            : "—");
      return `<tr>
        <td>${index + 1}</td>
        <td>${escapeHtml(s.name || "Learner")}</td>
        <td>${escapeHtml(grade)}</td>
        <td>${escapeHtml(s.monitoringStatus || "—")}</td>
        <td>${escapeHtml(risk)}</td>
        <td>${escapeHtml(aral)}</td>
      </tr>`;
    })
    .join("");

  const bodyHtml = `
    <div class="charts">
      ${renderBarChartHtml("Student performance distribution", perfBars)}
      ${renderBarChartHtml("Monitoring progress", monBars)}
    </div>

    ${renderDataTableHtml({
      headers: ["#", "Learner", "Grade / Avg", "Monitoring", "Risk", "ARAL"],
      rowsHtml: learnerRows,
      emptyText: "No learners in this class report.",
    })}

    <div class="summary-right">
      <div><strong>Learners:</strong> ${students.length}</div>
      <div><strong>Ungraded:</strong> ${ungradedCount}</div>
      <div><strong>Class average:</strong> ${escapeHtml(avg)}</div>
      <div><strong>Passing rate:</strong> ${escapeHtml(passLabel)}</div>
      <div><strong>At-risk (graded only):</strong> ${atRisk}</div>
      <div><strong>ARAL learners:</strong> ${classReport.aralEligible === false ? "—" : aralCount}</div>
    </div>
  `;

  const html = wrapCnhsPrintDocument({
    documentTitle: `Class Performance Report — ${section} · ${subject}`,
    letterheadSub: "CNHS Learn · Class Performance Report",
    title: "CLASS PERFORMANCE REPORT",
    subtitle: `${section} · ${subject} · ${quarter || "—"}`,
    metaRows: [
      [
        "Generated by",
        teacherName || classReport.teacherName || "Teacher",
      ],
      ["Coverage", schoolYear || classReport.schoolYear || "—"],
      ["Report category", "Academic performance"],
      ["Term", quarter || "—"],
      ["Report type", "Class report"],
      ["Date generated", dateGenerated],
    ],
    bodyHtml,
    signatureLabel: "Prepared and certified by Subject Teacher / Adviser:",
  });

  openPrintableHtml(html, {
    title: `Class-Performance-${section}-${subject}`,
    autoPrint: true,
  });
}
