import { downloadWorkbook } from "@/lib/reports/excelOfficialTemplate";
import { buildTeacherClassExcelReport } from "@/lib/reports/excelTeacherClassTemplate";
import { TERM_ALL_LABEL, termLabel } from "@/lib/academic/termLabels";
import { passingRateFromGrades } from "@/lib/teacher/reportsCalculations";
import { buildClassReportPreview } from "@/lib/teacher/reportsMappers";
import {
  chartRowsFromList,
  escapeHtml,
  renderBarChartHtml,
  renderDataTableHtml,
  renderKpiRowHtml,
  renderMetricGroupsHtml,
  wrapCnhsPrintDocument,
} from "@/lib/reports/cnhsPrintShell";
import { openPrintableHtml } from "@/lib/reports/openPrintableHtml";
import { buildTeacherExcelPayload } from "@/lib/reports/scopedExcelPayload";

/**
 * Download an HTML class/school report (no print dialog).
 * CNHS-branded shell (same look as Class Performance System Report).
 */
export function exportTeacherReportsPdf({
  teacherName,
  schoolYear,
  quarter,
  summary,
  classReports = [],
  charts = {},
  generatedAt = new Date(),
} = {}) {
  const dateGenerated = generatedAt.toLocaleString("en-PH", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const summaryHtml = renderMetricGroupsHtml([
    {
      label: "Scope",
      metrics: [
        ["Total classes", summary?.totalClasses ?? 0],
        ["Total learners", summary?.totalStudents ?? 0],
      ],
    },
    {
      label: "Academic",
      metrics: [
        [
          "Average class grade",
          summary?.averageClassGrade == null
            ? "—"
            : summary.averageClassGrade,
        ],
        [
          "Passing rate",
          summary?.passingRate == null ? "—" : `${summary.passingRate}%`,
        ],
        ["Highest subject", summary?.highestSubject || "—"],
        ["Lowest subject", summary?.lowestSubject || "—"],
      ],
    },
    {
      label: "Intervention",
      metrics: [
        ["ARAL learners", summary?.aralScreeningCount ?? 0],
        ["Classroom remedial", summary?.classroomRemedialCount ?? 0],
        [
          "Monitoring completion",
          `${summary?.monitoringCompletionRate ?? 0}%`,
        ],
        [
          "Under monitoring",
          summary?.learnersUnderMonitoring ?? 0,
        ],
      ],
    },
  ]);

  const tableRows = classReports
    .map(
      (row) => `<tr>
        <td>${escapeHtml(row.section ?? row.gradeSection)}</td>
        <td>${escapeHtml(row.subject)}</td>
        <td>${escapeHtml(row.students)}</td>
        <td>${escapeHtml(row.averageGrade)}</td>
        <td>${escapeHtml(row.aralScreeningDisplay ?? (row.aralEligible === false ? "—" : row.aralScreening))}</td>
        <td>${escapeHtml(row.classroomRemedial)}</td>
        <td>${escapeHtml(row.monitoringStatus)}</td>
      </tr>`
    )
    .join("");

  const bodyHtml = `
    <p class="section-label">Summary</p>
    ${summaryHtml}

    <p class="section-label">Class Reports</p>
    ${renderDataTableHtml({
      headers: [
        "Section",
        "Subject",
        "Students",
        "Average Grade",
        "ARAL Learners",
        "Classroom Remedial",
        "Monitoring Status",
      ],
      rowsHtml: tableRows,
      emptyText: "No class reports for the selected filters.",
    })}

    <p class="section-label">Charts</p>
    <div class="charts">
      ${renderBarChartHtml(
        "Student Performance Distribution",
        chartRowsFromList(charts.performanceDistribution)
      )}
      ${renderBarChartHtml(
        "ARAL Learners Distribution",
        chartRowsFromList(charts.aralDistribution)
      )}
      ${renderBarChartHtml(
        "Average Grade Per Subject",
        chartRowsFromList(
          charts.averageGradePerSubject,
          "subject",
          "average"
        )
      )}
      ${renderBarChartHtml(
        "Monitoring Progress",
        chartRowsFromList(charts.monitoringProgress)
      )}
    </div>
  `;

  const html = wrapCnhsPrintDocument({
    documentTitle: `Teacher Report — ${teacherName || "CNHS"}`,
    letterheadSub: "CNHS Learn · Teacher Class Performance Report",
    title: "TEACHER CLASS PERFORMANCE REPORT",
    subtitle: `${schoolYear || "—"} · ${quarter || "—"}`,
    metaRows: [
      ["Generated by", teacherName || "Teacher"],
      ["Coverage", schoolYear || "—"],
      ["Report category", "Academic performance"],
      ["Term", quarter || "—"],
      ["Report type", "Multi-class summary"],
      ["Date generated", dateGenerated],
    ],
    bodyHtml,
    signatureLabel: "Prepared and certified by Subject Teacher / Adviser:",
  });

  openPrintableHtml(html, {
    title: `Teacher-Report-${teacherName || "CNHS"}`,
    autoPrint: true,
  });
}

function resolveTermLabel(quarter) {
  if (!quarter) return TERM_ALL_LABEL;
  return termLabel(quarter);
}

function formatSchoolYearForFilename(value) {
  const year = String(value ?? "").trim();
  if (!year) return "SY";
  if (/^sy\b/i.test(year)) return year;
  return `SY ${year}`;
}

function windowsSafeFilename(name) {
  return (
    String(name ?? "")
      .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 150) || "Teacher Report"
  );
}

function gradeSectionForFilename(classReports = []) {
  const sections = [
    ...new Set(
      classReports
        .map((row) => row?.gradeSection || row?.section)
        .map((value) => String(value ?? "").trim())
        .filter(Boolean)
    ),
  ];
  if (sections.length === 1) return sections[0];
  return "All Classes";
}

/** {Teacher Name} — {Grade & Section} — {School Year} — {Term}.xlsx */
function teacherClassReportFilename({
  teacherName,
  gradeSection,
  schoolYear,
  quarter,
} = {}) {
  const name = String(teacherName || "Teacher").trim() || "Teacher";
  const section =
    String(gradeSection || "All Classes").trim() || "All Classes";
  const year = formatSchoolYearForFilename(schoolYear);
  const term = resolveTermLabel(quarter);
  return `${windowsSafeFilename(`${name} — ${section} — ${year} — ${term}`)}.xlsx`;
}

function normalizeTeacherClassRow(row) {
  if (!row) return null;
  return {
    section: row.section ?? row.gradeSection,
    subject: row.subject,
    students: row.students,
    averageGrade: row.averageGrade,
    averageGradeValue:
      typeof row.averageGrade === "number"
        ? row.averageGrade
        : row.averageGradeValue ?? null,
    aralScreeningDisplay:
      row.aralScreeningDisplay ??
      (row.aralEligible === false ? "—" : row.aralScreening),
    classroomRemedial: row.classroomRemedial ?? "—",
    monitoringStatus: row.monitoringStatus ?? "—",
    schoolYear: row.schoolYear,
    quarter: row.quarter,
    teacherName: row.teacherName,
    aralEligible: row.aralEligible,
    aralScreening: row.aralScreening,
    classroomRemedialRecommended: Boolean(row.classroomRemedialRecommended),
    classStudents: row.classStudents,
    subjectGrades: row.subjectGrades,
  };
}

function reportScopeLabel(classReports = []) {
  if (classReports.length === 1) {
    const row = classReports[0];
    const section = String(row?.gradeSection || row?.section || "").trim();
    const subject = String(row?.subject || "").trim();
    return [section, subject].filter(Boolean).join(" — ") || "All Classes";
  }
  return gradeSectionForFilename(classReports);
}

function buildTeacherCoverChartSeries(charts = {}) {
  const size = { width: 420, height: 240 };
  const series = [];

  if (charts.performanceDistribution?.length) {
    series.push({
      title: "Student Performance Distribution",
      tableTitle: "Student Performance",
      chartType: "pie",
      categoryHeader: "Band",
      valueHeader: "Learners",
      footer: "total",
      ...size,
      rows: charts.performanceDistribution.map((row) => ({
        category: row.name,
        value: row.value,
      })),
    });
  }

  if (charts.averageGradePerSubject?.length) {
    series.push({
      title: "Average Grade Per Subject",
      chartType: "bar",
      categoryHeader: "Subject",
      valueHeader: "Average",
      footer: "average",
      ...size,
      rows: charts.averageGradePerSubject.map((row) => ({
        category: row.subject ?? row.name,
        value: row.average ?? row.value,
      })),
    });
  }

  if (charts.monitoringProgress?.length) {
    series.push({
      title: "Monitoring Progress",
      chartType: "pie",
      categoryHeader: "Status",
      valueHeader: "Count",
      footer: "total",
      ...size,
      rows: charts.monitoringProgress.map((row) => ({
        category: row.name,
        value: row.value,
      })),
    });
  }

  return series;
}

function subjectAverageExtremes(rows = []) {
  const values = rows
    .map((row) => Number(row.average ?? row.value))
    .filter((n) => Number.isFinite(n));
  if (!values.length) return { highest: null, lowest: null };
  return {
    highest: Math.max(...values),
    lowest: Math.min(...values),
  };
}

/**
 * Export class report rows to official CNHS Excel workbook.
 * Cover metrics, charts, table, and narratives all use the same scoped payload.
 */
export async function exportTeacherReportsExcel({
  classReports = [],
  summary = {},
  charts = {},
  teacherName = "Teacher",
  schoolYear = "",
  quarter = "",
  filename = null,
  preview = null,
} = {}) {
  const rows = classReports.map(normalizeTeacherClassRow).filter(Boolean);
  const scoped = buildTeacherExcelPayload({
    classReports: classReports.filter(Boolean),
    summary,
    charts,
  });
  const qLabel = resolveTermLabel(quarter);
  const {
    totalClasses,
    totalStudents,
    aralScreeningCount: aralLearners,
    classroomRemedialCount: classroomRemedial,
    averageClassGrade: averageGrade,
    monitoringCompletionRate: monitoringRate,
  } = scoped.summary;
  const { highest, lowest } = subjectAverageExtremes(
    scoped.charts.averageGradePerSubject
  );

  const snap = preview;
  const academic = snap?.academic;
  const interventions = snap?.interventions;
  const coverMetrics = snap
    ? [
        {
          label: "Roster",
          value: academic?.rosterSize ?? totalStudents,
          tone: "default",
        },
        {
          label: "Graded",
          value: academic?.gradedCount ?? 0,
          tone: "default",
        },
        {
          label: "Ungraded",
          value: academic?.ungradedCount ?? 0,
          tone: "default",
        },
        {
          label: "Class Average",
          value: academic?.classAverage ?? "—",
          tone: "green",
        },
        {
          label: "Passing Rate",
          value: academic?.passingRate ?? "—",
          tone: "green",
        },
        {
          label: "Below 75",
          value: academic?.belowPassingCount ?? 0,
          tone:
            Number(academic?.belowPassingCount) > 0 ? "amber" : "green",
        },
        {
          label: "ARAL Learners",
          value: interventions?.aral ?? "—",
          tone: "default",
        },
        {
          label: "Classroom Remedial",
          value: interventions?.classroomRemedial ?? "No",
          tone: interventions?.classroomRemedialRecommended ? "amber" : "green",
        },
      ]
    : [
        { label: "Total Classes", value: totalClasses, tone: "default" },
        { label: "Total Students", value: totalStudents, tone: "default" },
        {
          label: "ARAL Learners",
          value: aralLearners,
          tone: Number(aralLearners) > 0 ? "amber" : "green",
        },
        {
          label: "Classroom Remedial Classes",
          value: classroomRemedial,
          tone: Number(classroomRemedial) > 0 ? "amber" : "green",
        },
        {
          label: "Average Class Grade",
          value: averageGrade ?? "—",
          tone:
            averageGrade != null && Number(averageGrade) < 75 ? "amber" : "green",
        },
        {
          label: "Monitoring Completion",
          value: `${monitoringRate}%`,
          tone: Number(monitoringRate) < 100 ? "amber" : "green",
        },
      ];

  const learnerColumns = [
    { key: "n", header: "#", width: 8, numeric: true },
    { key: "name", header: "Learner", width: 28 },
    { key: "grade", header: "Grade", width: 12 },
    { key: "risk", header: "Risk", width: 14 },
  ];
  const toLearnerRows = (list = []) =>
    list.map((s, index) => ({
      n: index + 1,
      name: s.name,
      grade: s.gradeLabel,
      risk: s.risk,
    }));

  const extraTables = snap
    ? [
        {
          sheetName: "FAILING",
          title: `FAILING (<75) — ${snap.termLabel || qLabel}`,
          columns: learnerColumns,
          rows: toLearnerRows(snap.failingLearners),
        },
        {
          sheetName: "UNGRADED",
          title: `UNGRADED — ${snap.termLabel || qLabel}`,
          columns: learnerColumns,
          rows: toLearnerRows(snap.ungradedLearners),
        },
      ]
    : [];

  const workbook = await buildTeacherClassExcelReport({
    meta: {
      reportTitle: "Teacher Class Performance Report",
      schoolYear: schoolYear || "—",
      quarter: qLabel,
      generatedBy: teacherName || "Teacher",
      totalRecords: rows.length,
      reportScope: reportScopeLabel(classReports),
    },
    metrics: coverMetrics,
    chartSeries: buildTeacherCoverChartSeries(scoped.charts),
    table: {
      sheetName: "Detailed Report",
      title: `Class Reports — ${teacherName || "Teacher"} · ${schoolYear || "SY"} · ${qLabel}`,
      columns: [
        { key: "section", header: "Section", width: 18 },
        { key: "subject", header: "Subject", width: 16 },
        { key: "students", header: "Students", width: 11, numeric: true },
        {
          key: "averageGrade",
          header: "Avg Grade",
          width: 12,
          numeric: true,
          gradeRule: true,
        },
        { key: "aralScreeningDisplay", header: "ARAL Learners", width: 14 },
        { key: "classroomRemedial", header: "Classroom Remedial", width: 18 },
        {
          key: "monitoringStatus",
          header: "Monitoring Status",
          width: 18,
          statusRule: true,
        },
      ],
      rows,
    },
    narrativeContext: {
      totalClasses,
      totalStudents,
      averageGrade,
      highestAverage: highest,
      lowestAverage: lowest,
      atRisk: scoped.atRisk,
      aralLearners,
      classroomRemedial,
      monitoringRate,
    },
    extraTables,
  });

  const { appendInterventionSheet } = await import(
    "@/lib/reports/interventionCaseloadExport"
  );
  await appendInterventionSheet(workbook, {
    learners: classReports.flatMap((row) => row.classStudents ?? []),
  });

  const resolvedFilename =
    filename ||
    teacherClassReportFilename({
      teacherName,
      gradeSection: gradeSectionForFilename(classReports),
      schoolYear,
      quarter,
    });

  await downloadWorkbook(workbook, resolvedFilename);
}

/**
 * Export a single class workbook — summary + charts rebuilt for that class only.
 */
export async function exportClassReportExcel(classReport, charts = {}, preview = null) {
  if (!classReport) return;

  const filename = teacherClassReportFilename({
    teacherName: classReport.teacherName,
    gradeSection: classReport.gradeSection ?? classReport.section,
    schoolYear: classReport.schoolYear,
    quarter: classReport.quarter,
  });

  const snap =
    preview ||
    buildClassReportPreview(classReport, {
      teacherName: classReport.teacherName,
      schoolYear: classReport.schoolYear,
      quarter: classReport.quarter,
    });

  await exportTeacherReportsExcel({
    classReports: [classReport],
    summary: {},
    charts,
    teacherName: classReport.teacherName,
    schoolYear: classReport.schoolYear,
    quarter: classReport.quarter,
    filename,
    preview: snap,
  });
}

export async function exportSingleClassReportExcel(classReport, charts = {}) {
  if (!classReport) return;
  await exportClassReportExcel(classReport, charts);
}

function gradeBucketLabel(grade) {
  const n =
    grade === null || grade === undefined || grade === ""
      ? NaN
      : Number(grade);
  if (!Number.isFinite(n)) return "Ungraded";
  if (n >= 90) return "90-100";
  if (n >= 85) return "85-89";
  if (n >= 75) return "75-84";
  return "Below 75";
}

/** True when learner has no usable subject/term grade. */
function isUngradedGrade(grade) {
  if (grade === null || grade === undefined || grade === "" || grade === "—") {
    return true;
  }
  return !Number.isFinite(Number(grade));
}

function resolveLearnerGrade(student) {
  return student?.classSubjectGrade ?? student?.grade ?? student?.averageGrade;
}

/**
 * Risk for reports: Ungraded → "—"; only graded learners can be High/at-risk.
 */
function learnerRiskLabel(student) {
  const grade = resolveLearnerGrade(student);
  if (isUngradedGrade(grade)) return "—";
  const n = Number(grade);
  if (n < 75) return student.riskLevel === "Moderate" ? "Moderate" : "High";
  if (n <= 84) return student.riskLevel === "High" ? "High" : "Moderate";
  return student.riskLevel === "High" || student.riskLevel === "Moderate"
    ? student.riskLevel
    : "Low";
}

function isGradedAtRisk(student) {
  const grade = resolveLearnerGrade(student);
  if (isUngradedGrade(grade)) return false;
  const n = Number(grade);
  if (n < 75) return true;
  if (student.atRisk && n < 85) return true;
  return student.riskLevel === "High" && n < 85;
}

function buildClassPerfBuckets(classStudents = []) {
  const order = ["90-100", "85-89", "75-84", "Below 75", "Ungraded"];
  const counts = Object.fromEntries(order.map((k) => [k, 0]));
  for (const s of classStudents) {
    counts[gradeBucketLabel(resolveLearnerGrade(s))] += 1;
  }
  return order
    .filter((k) => k !== "Ungraded" || counts[k] > 0)
    .map((name) => ({ name, value: counts[name] }));
}

function buildClassMonitoringBars(classStudents = []) {
  const labels = [
    "Not Started",
    "Ongoing",
    "Needs Follow-up",
    "Improved",
    "Completed",
  ];
  const counts = Object.fromEntries(labels.map((k) => [k, 0]));
  for (const s of classStudents) {
    const status = String(s.monitoringStatus || "Not Started");
    if (counts[status] != null) counts[status] += 1;
    else counts["Not Started"] += 1;
  }
  return labels.map((name) => ({ name, value: counts[name] }));
}

/**
 * Formal one-class Class Performance Report (printable HTML → PDF).
 * Uses the same snapshot as Teacher Report Preview so files match the modal.
 */
export function exportClassPerformanceSystemReport({
  classReport,
  preview = null,
  teacherName,
  schoolYear,
  quarter,
  generatedAt = new Date(),
} = {}) {
  if (!classReport && !preview) {
    throw new Error("Select a class to generate a report.");
  }

  const snap =
    preview ||
    buildClassReportPreview(classReport, {
      teacherName,
      schoolYear,
      quarter,
    });
  if (!snap) throw new Error("Select a class to generate a report.");

  const dateGenerated = (
    generatedAt instanceof Date ? generatedAt : new Date(generatedAt)
  ).toLocaleString("en-PH", {
    dateStyle: "long",
    timeStyle: "short",
  });
  const info = snap.classInformation || {};
  const academic = snap.academic || {};
  const interventions = snap.interventions || {};
  const section = info.gradeSection || classReport?.gradeSection || "Section";
  const subject = info.subject || classReport?.subject || "Subject";
  const termName = snap.termLabel || info.term || quarter || "—";
  const sy = info.schoolYear || schoolYear || "—";

  const learnerRowHtml = (rows, emptyText) =>
    renderDataTableHtml({
      headers: ["#", "Learner", "Grade", "Risk"],
      rowsHtml: (rows ?? [])
        .map(
          (s, index) => `<tr>
        <td>${index + 1}</td>
        <td>${escapeHtml(s.name || "Learner")}</td>
        <td>${escapeHtml(s.gradeLabel ?? "—")}</td>
        <td>${escapeHtml(s.risk || "—")}</td>
      </tr>`
        )
        .join(""),
      emptyText,
    });

  const bucketBars = (snap.performanceBuckets ?? []).map((row) => ({
    name: row.label,
    value: row.learners,
  }));

  const bodyHtml = `
    <p class="note">Generated from E-Record · ${escapeHtml(termName)} · ${escapeHtml(sy)}. Empty E-Record cells are UNGRADED, not 0. Attendance is not a prediction input.</p>
    ${renderKpiRowHtml([
      ["Class average", academic.classAverage ?? "—"],
      ["Passing rate", academic.passingRate ?? "—"],
      ["Below 75", academic.belowPassingCount ?? 0],
      ["Ungraded", academic.ungradedCount ?? 0],
    ])}
    ${renderMetricGroupsHtml([
      {
        label: "Academic",
        metrics: [
          ["Roster", academic.rosterSize ?? 0],
          ["Graded", academic.gradedCount ?? 0],
          ["Passing among graded", academic.passingRateDetail ?? "—"],
          ["Below 75 (% of graded)", academic.belowPassingPercent ?? 0],
        ],
      },
      {
        label: "Interventions & follow-up",
        metrics: [
          ["ARAL Learners", interventions.aral ?? "—"],
          ["Classroom Remedial", interventions.classroomRemedial ?? "No"],
          ["Monitoring completed", interventions.monitoringCompleted ?? 0],
          ["Still under monitoring", interventions.stillUnderMonitoring ?? 0],
          ["Showing improvement", interventions.showingImprovement ?? 0],
          ["Needs follow-up", interventions.needsFollowUp ?? 0],
        ],
      },
    ])}
    <p class="section-label">Performance in this class</p>
    ${renderBarChartHtml("FAILING / MODERATE / PASSING / UNGRADED", bucketBars)}
    <p class="section-label">FAILING</p>
    ${learnerRowHtml(snap.failingLearners, "No failing learners this term.")}
    <p class="section-label">UNGRADED</p>
    ${learnerRowHtml(snap.ungradedLearners, "No ungraded learners this term.")}
  `;

  const html = wrapCnhsPrintDocument({
    documentTitle: `Class Performance Report — ${section} · ${subject}`,
    letterheadSub: "CNHS Learn · Class Performance Report",
    title: "CLASS PERFORMANCE REPORT",
    subtitle: `${section} · ${subject} · ${termName}`,
    metaRows: [
      ["Generated by", teacherName || info.teacher || "Teacher"],
      ["Coverage", sy],
      ["Report category", "Academic performance"],
      ["Term", termName],
      ["Report type", "Class report"],
      ["Date generated", snap.generatedAtLabel || dateGenerated],
    ],
    bodyHtml,
    signatureLabel: "Prepared and certified by Subject Teacher / Adviser:",
  });

  openPrintableHtml(html, {
    title: `Class-Performance-${section}-${subject}`,
    autoPrint: true,
  });
}
