import { RowActions } from "@/components/reports/ActionButtons";
import { FileTypeBadge } from "@/components/reports/ActionButtons";
import CategoryBadge from "@/components/reports/CategoryBadge";
import StatusBadge from "@/components/reports/StatusBadge";

const headers = [
  "Report Name",
  "Category",
  "Generated By",
  "Generated Date",
  "File Type",
  "Status",
  "Actions",
];

export default function ReportsTable({ reports, onPreview }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[920px] text-left">
        <thead className="bg-slate-50/80">
          <tr>
            {headers.map((header) => (
              <th
                key={header}
                scope="col"
                className="px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.08em] text-slate-500"
              >
                {header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {reports.map((report) => (
            <tr key={report.id} className="border-t border-slate-100 transition-colors hover:bg-slate-50/60">
              <td className="px-4 py-4 text-xs font-semibold text-slate-800">{report.reportName}</td>
              <td className="px-4 py-4">
                <CategoryBadge value={report.category} />
              </td>
              <td className="px-4 py-4 text-xs text-slate-500">{report.generatedBy}</td>
              <td className="px-4 py-4 text-xs text-slate-500">{report.generatedDate}</td>
              <td className="px-4 py-4">
                <FileTypeBadge value={report.fileType} />
              </td>
              <td className="px-4 py-4">
                <StatusBadge value={report.status} />
              </td>
              <td className="px-4 py-4">
                <RowActions onPreview={() => onPreview(report)} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
