export default function ReportInformation({ report }) {
  const details = [
    ["Generated By", report.generatedBy],
    ["Generated Date", report.generatedDate],
    ["School Year", report.schoolYear],
    ["Quarter", report.quarter],
    ["File Format", report.fileType],
    ["Status", report.status],
  ];

  return (
    <section>
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-[0.08em] text-slate-400">
        Report Information
      </h3>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <dl>
          {details.map(([label, value], index) => (
            <div
              key={label}
              className={`flex items-center justify-between gap-4 px-5 py-3.5 ${
                index !== details.length - 1 ? "border-b border-slate-100" : ""
              }`}
            >
              <dt className="text-xs font-medium text-slate-400">{label}</dt>
              <dd className="text-sm font-semibold text-slate-800">{value}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}
