"use client";

import { StatusPill, interventionStyles } from "@/components/teacher/my-classes/shared";

export default function InterventionSummary({ intervention }) {
  return (
    <section className="rounded-xl border border-slate-100 bg-white p-3 shadow-[0_6px_16px_rgba(15,23,42,0.04)]">
      <div className="flex items-start justify-between gap-3">
        <h3 className="text-sm font-semibold text-slate-900">Personalized Learning Plan</h3>
        <StatusPill value={intervention.planStatus} />
      </div>

      <p className="mt-1 text-[11px] text-slate-400">
        Read-only system recommendation · Generated by {intervention.generatedBy}
      </p>

      <dl className="mt-4 space-y-3">
        {[
          ["Learning Goal", intervention.learningGoal],
          ["Target Outcome", intervention.targetOutcome],
          ["Recommended Intervention", intervention.recommendedIntervention],
          ["Monitoring Frequency", intervention.monitoringFrequency],
        ].map(([label, value]) => (
          <div key={label}>
            <dt className="text-[10px] font-medium uppercase tracking-[0.06em] text-slate-400">
              {label}
            </dt>
            <dd className="mt-1 text-[12px] font-medium text-slate-700">{value}</dd>
          </div>
        ))}
      </dl>

      <div className="mt-4 grid grid-cols-1 gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2">
        <div>
          <p className="text-[10px] font-medium uppercase tracking-[0.06em] text-slate-400">
            Current Status
          </p>
          <div className="mt-1.5">
            <StatusPill value={intervention.currentStatus} styles={interventionStyles} />
          </div>
        </div>
        <div>
          <p className="text-[10px] font-medium uppercase tracking-[0.06em] text-slate-400">
            Monitoring
          </p>
          <p className="mt-1.5 text-[12px] font-semibold text-slate-700">
            {intervention.monitoringStatus}
          </p>
        </div>
        <div>
          <p className="text-[10px] font-medium uppercase tracking-[0.06em] text-slate-400">
            Parent Conference
          </p>
          <p className="mt-1.5 text-[12px] font-semibold text-slate-700">
            {intervention.parentConference}
          </p>
        </div>
        <div>
          <p className="text-[10px] font-medium uppercase tracking-[0.06em] text-slate-400">
            ARAL Enrollment
          </p>
          <p className="mt-1.5 text-[12px] font-semibold text-slate-700">
            {intervention.aralEnrollment}
          </p>
        </div>
      </div>
    </section>
  );
}
