/**
 * Admin User Management → Export Users (Excel).
 * Teachers + Head Teachers only. No passwords, auth IDs, or placeholder columns.
 */

import {
  CNHS_EXCEL_BRAND,
  applyPrintSettings,
  createWorkbook,
  downloadWorkbook,
} from "@/lib/reports/excelOfficialTemplate";

function asText(value) {
  if (value === null || value === undefined || value === "") return "—";
  return String(value);
}

function thinBorder() {
  const edge = {
    style: "thin",
    color: { argb: `FF${CNHS_EXCEL_BRAND.border}` },
  };
  return { top: edge, left: edge, bottom: edge, right: edge };
}

function formatStamp(date = new Date()) {
  return {
    dateGenerated: date.toLocaleDateString("en-PH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    timeGenerated: date.toLocaleTimeString("en-PH", {
      hour: "2-digit",
      minute: "2-digit",
    }),
    fileDate: date.toISOString().slice(0, 10),
  };
}

function countByRole(users = [], role) {
  return users.filter((user) => user.role === role).length;
}

function buildCounts(users = [], summaryCards = []) {
  const byId = Object.fromEntries(
    (summaryCards ?? []).map((card) => [card.id, card.count])
  );
  const active =
    byId.active ??
    users.filter((user) => user.status === "Active").length;
  const total = byId.total ?? users.length;
  return {
    total,
    teachers: byId.teachers ?? countByRole(users, "Teacher"),
    principals: byId.principals ?? byId["head-teachers"] ?? countByRole(users, "Principal"),
    active,
    inactive: Math.max(0, total - active),
  };
}

function paintSummarySheet(workbook, { counts, generatedBy, stamp }) {
  const sheet = workbook.addWorksheet("User Summary", {
    views: [{ showGridLines: false }],
  });

  sheet.getColumn(1).width = 4;
  sheet.getColumn(2).width = 28;
  sheet.getColumn(3).width = 22;
  sheet.getColumn(4).width = 4;
  sheet.getColumn(5).width = 28;
  sheet.getColumn(6).width = 22;

  let row = 2;

  sheet.mergeCells(row, 2, row, 6);
  const school = sheet.getCell(row, 2);
  school.value = CNHS_EXCEL_BRAND.schoolName;
  school.font = {
    name: "Calibri",
    size: 16,
    bold: true,
    color: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
  };
  school.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(row).height = 24;
  row += 1;

  sheet.mergeCells(row, 2, row, 6);
  const system = sheet.getCell(row, 2);
  system.value = CNHS_EXCEL_BRAND.systemName;
  system.font = {
    name: "Calibri",
    size: 11,
    color: { argb: `FF${CNHS_EXCEL_BRAND.slate}` },
  };
  system.alignment = { horizontal: "center", vertical: "middle" };
  row += 2;

  sheet.mergeCells(row, 2, row, 6);
  const title = sheet.getCell(row, 2);
  title.value = "User Directory";
  title.font = {
    name: "Calibri",
    size: 14,
    bold: true,
    color: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
  };
  title.alignment = { horizontal: "center", vertical: "middle" };
  row += 2;

  const meta = [
    ["Date Generated", stamp.dateGenerated],
    ["Time Generated", stamp.timeGenerated],
    ["Generated By", asText(generatedBy || "Principal / Admin")],
    ["Scope", "Teachers and Principal"],
  ];

  for (const [label, value] of meta) {
    const labelCell = sheet.getCell(row, 2);
    labelCell.value = label;
    labelCell.font = {
      name: "Calibri",
      size: 11,
      bold: true,
      color: { argb: `FF${CNHS_EXCEL_BRAND.slate}` },
    };
    labelCell.border = thinBorder();

    sheet.mergeCells(row, 3, row, 6);
    const valueCell = sheet.getCell(row, 3);
    valueCell.value = value;
    valueCell.font = {
      name: "Calibri",
      size: 11,
      color: { argb: `FF${CNHS_EXCEL_BRAND.slateDark}` },
    };
    valueCell.border = thinBorder();
    for (let c = 4; c <= 6; c += 1) {
      sheet.getCell(row, c).border = thinBorder();
    }
    row += 1;
  }

  row += 2;
  sheet.mergeCells(row, 2, row, 6);
  const summaryTitle = sheet.getCell(row, 2);
  summaryTitle.value = "Account Summary";
  summaryTitle.font = {
    name: "Calibri",
    size: 12,
    bold: true,
    color: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
  };
  row += 1;

  sheet.mergeCells(row, 2, row, 5);
  for (let c = 2; c <= 6; c += 1) {
    const cell = sheet.getCell(row, c);
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
    };
    cell.font = {
      name: "Calibri",
      size: 11,
      bold: true,
      color: { argb: `FF${CNHS_EXCEL_BRAND.white}` },
    };
    cell.border = thinBorder();
    cell.alignment = { horizontal: "center", vertical: "middle" };
  }
  sheet.getCell(row, 2).value = "Metric";
  sheet.getCell(row, 6).value = "Value";
  sheet.getRow(row).height = 20;
  row += 1;

  const metrics = [
    ["Total Users", counts.total],
    ["Teachers", counts.teachers],
    ["Principals", counts.principals ?? counts.headTeachers ?? 0],
    ["Active Accounts", counts.active],
    ["Inactive Accounts", counts.inactive],
  ];

  metrics.forEach(([label, value], index) => {
    const zebra =
      index % 2 === 1 ? CNHS_EXCEL_BRAND.zebraAlt : CNHS_EXCEL_BRAND.white;
    sheet.mergeCells(row, 2, row, 5);
    for (let c = 2; c <= 6; c += 1) {
      const cell = sheet.getCell(row, c);
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: `FF${zebra}` },
      };
      cell.border = thinBorder();
    }
    const labelCell = sheet.getCell(row, 2);
    labelCell.value = label;
    labelCell.font = {
      name: "Calibri",
      size: 11,
      color: { argb: `FF${CNHS_EXCEL_BRAND.slateDark}` },
    };
    labelCell.alignment = { horizontal: "left", vertical: "middle", indent: 1 };

    const valueCell = sheet.getCell(row, 6);
    valueCell.value = value;
    valueCell.font = {
      name: "Calibri",
      size: 11,
      bold: true,
      color: { argb: `FF${CNHS_EXCEL_BRAND.valueAccent}` },
    };
    valueCell.alignment = { horizontal: "center", vertical: "middle" };
    row += 1;
  });

  row += 2;
  sheet.mergeCells(row, 2, row, 6);
  const note = sheet.getCell(row, 2);
  note.value =
    "This directory lists Teacher and Principal accounts only. Passwords and authentication identifiers are never exported.";
  note.font = {
    name: "Calibri",
    size: 9,
    italic: true,
    color: { argb: `FF${CNHS_EXCEL_BRAND.slate}` },
  };
  note.alignment = { horizontal: "center", wrapText: true };
  sheet.getRow(row).height = 32;

  applyPrintSettings(sheet, {
    landscape: false,
    title: "User Directory Summary",
  });
}

function paintDirectorySheet(workbook, users = []) {
  const sheet = workbook.addWorksheet("User Directory", {
    views: [{ showGridLines: false }],
  });

  const columns = [
    { key: "employeeId", header: "Employee Number", width: 16 },
    { key: "fullName", header: "Full Name", width: 28 },
    { key: "username", header: "Username", width: 16 },
    { key: "role", header: "Role", width: 14 },
    { key: "learningArea", header: "Learning Area", width: 18 },
    { key: "assignedClasses", header: "Assigned Classes", width: 36 },
    { key: "email", header: "Email", width: 28 },
    { key: "phone", header: "Contact Number", width: 16 },
    { key: "status", header: "Account Status", width: 14 },
    { key: "createdDate", header: "Date Created", width: 14 },
  ];

  columns.forEach((col, index) => {
    sheet.getColumn(index + 1).width = col.width;
  });

  let row = 1;
  sheet.mergeCells(row, 1, row, columns.length);
  const title = sheet.getCell(row, 1);
  title.value = "CNHS User Directory — Teachers & Principal";
  title.font = {
    name: "Calibri",
    size: 13,
    bold: true,
    color: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
  };
  title.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(row).height = 22;
  row += 2;

  const headerRowIndex = row;
  columns.forEach((col, index) => {
    const cell = sheet.getCell(row, index + 1);
    cell.value = col.header;
    cell.font = {
      name: "Calibri",
      size: 10,
      bold: true,
      color: { argb: `FF${CNHS_EXCEL_BRAND.white}` },
    };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: `FF${CNHS_EXCEL_BRAND.greenDark}` },
    };
    cell.border = thinBorder();
    cell.alignment = {
      horizontal: "center",
      vertical: "middle",
      wrapText: true,
    };
  });
  sheet.getRow(row).height = 22;
  row += 1;

  const sorted = [...users].sort((a, b) =>
    String(a.fullName || "").localeCompare(String(b.fullName || ""), "en", {
      sensitivity: "base",
    })
  );

  sorted.forEach((user, index) => {
    const zebra =
      index % 2 === 1 ? CNHS_EXCEL_BRAND.zebra : CNHS_EXCEL_BRAND.white;
    const values = [
      asText(user.employeeId),
      asText(user.fullName),
      asText(user.username),
      asText(user.role),
      asText(user.learningArea),
      Array.isArray(user.assignedClasses) && user.assignedClasses.length
        ? user.assignedClasses.join(", ")
        : "—",
      asText(user.email),
      asText(user.phone),
      asText(user.status),
      asText(user.createdDate),
    ];

    values.forEach((value, colIndex) => {
      const cell = sheet.getCell(row, colIndex + 1);
      cell.value = value;
      cell.font = {
        name: "Calibri",
        size: 10,
        color: { argb: `FF${CNHS_EXCEL_BRAND.slateDark}` },
      };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: `FF${zebra}` },
      };
      cell.border = thinBorder();
      cell.alignment = {
        horizontal: colIndex === 1 || colIndex === 5 || colIndex === 6 ? "left" : "center",
        vertical: "middle",
        wrapText: colIndex === 5,
      };
    });
    sheet.getRow(row).height = 18;
    row += 1;
  });

  if (!sorted.length) {
    sheet.mergeCells(row, 1, row, columns.length);
    const empty = sheet.getCell(row, 1);
    empty.value = "No users available to export.";
    empty.font = {
      name: "Calibri",
      size: 11,
      color: { argb: `FF${CNHS_EXCEL_BRAND.slate}` },
    };
    empty.alignment = { horizontal: "center" };
  }

  sheet.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex, column: columns.length },
  };
  sheet.views = [
    { state: "frozen", ySplit: headerRowIndex, showGridLines: false },
  ];

  applyPrintSettings(sheet, {
    landscape: true,
    title: "User Directory",
    printTitlesRow: `${headerRowIndex}:${headerRowIndex}`,
  });

  return sheet;
}

/**
 * Export managed users (Teachers + Principal) to a 2-sheet Excel workbook.
 */
export async function exportManagedUsersExcel({
  users = [],
  summaryCards = [],
  generatedBy = "Principal / Admin",
  filename = null,
} = {}) {
  if (!Array.isArray(users) || users.length === 0) {
    throw new Error("No users available to export.");
  }

  const stamp = formatStamp();
  const counts = buildCounts(users, summaryCards);
  const workbook = createWorkbook();

  paintSummarySheet(workbook, { counts, generatedBy, stamp });
  paintDirectorySheet(workbook, users);

  const resolvedFilename =
    filename || `CNHS_User_Directory_${stamp.fileDate}.xlsx`;

  await downloadWorkbook(workbook, resolvedFilename);
  return { filename: resolvedFilename, counts };
}
